version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:10.16-browsers-legacy
      - image: circleci/python:3.6.5

jobs:
  build:
    executor: default
    steps:
      - checkout

  build-master:
    executor: default
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: .

  test:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run: yarn test

  deploy-master:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run: sudo pip install awscli
      - run: yarn deploy

workflows:
  version: 2
  deploy:
    jobs:
      - build-master
      - test:
          requires:
            - build-master
      - deploy-master:
          requires:
            - test